name: Update TV.m3u

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  update_tv_m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas
          pip install requests

      - name: Pull changes from remote
        run: |
          git pull origin main

      - name: Run update_links.py
        run: |
          python update_links.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Update TV.m3u file"
          git push origin main
