name: Update TV.m3u

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update_tv_m3u:
    runs-on: windows-latest
    # Use Node.js 20 by default
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Get public IP address
        run: |
          python -c "import requests; print(requests.get('https://httpbin.org/ip').json()['origin'])"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas
          pip install requests

      - name: Pull changes from remote
        run: |
          git pull origin main

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run update_links.py
        run: |
          python update_links.py

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update TV.m3u file"
          git push origin main
